sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1111
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tBdRn8adamA9gXP1tkK
    access-key-secret: ZcLgFJHx8DnWxuIKqrMneqnaTy48TJ
    bucket-name: web-cangqiongwu
  redis:
    port: 6379
    database: 10
    host: localhost
    auth: "123456"